# Numpy

In [1]:
import numpy as np

## Data listesinden Numpy Array Oluşturmak

In [2]:
data_list=[1,2,3] 

In [3]:
arr = np.array(data_list)

In [4]:
 arr

array([1, 2, 3])

In [5]:
data_list2 = [[10,20,30],[40,50,60],[70,80,90]]

In [6]:
arr2 = np.array(data_list2)

In [7]:
arr2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

## np.array()

In [8]:
# Bir numpy metodunun nasıl çalıştığıyla ilgili bilgi almak için Shift+Tab tuşlarını kullanabiliriz!

In [9]:
arr3 = np.array([1,2,3,4,5]) # önceden oluşturmak zorunda değiliz!

In [10]:
arr3

array([1, 2, 3, 4, 5])

In [11]:
arr3[0]

1

In [12]:
arr2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [13]:
arr2[2,2] # 2. sütun 2. sıra (0'dan başlıyor...)

90

In [14]:
arr2[0,1]

20

In [15]:
np.array([1,2,3])

array([1, 2, 3])

In [16]:
np.array([1,2,3],[4,5,6]) # hata verir!

TypeError: data type not understood

In [17]:
np.array([[1,2,3],[4,5,6]]) # iki boyutlu olduğunu belirtmek için iç içe köşeli parantez kullanırız.

array([[1, 2, 3],
       [4, 5, 6]])

# Numpy Array hakkında bilgi edinmek

In [18]:
a = np.array([2,33,56,78,90,101,125,257,313])

## np.array().ndim

In [19]:
a.ndim # array'in boyut sayısını döndürür.

1

In [20]:
np.array([1,2,3]).ndim

1

In [21]:
np.array([[1,2]]).ndim # 2 boyutlu olduğu için 2 değerini döndürür.

2

## np.array().shape

In [22]:
np.array([11,22,33,44]).shape # array'in satır sütun bilgilerini döndürür.

(4,)

In [23]:
np.array([[0,1],[2,3]]).shape # 2x2'lik bir matris olduğu için (2,2) şeklinde tuple döndürür.

(2, 2)

## np.array().size

In [24]:
np.array([2,3,4,5,6]).size # array'in eleman sayısını döndürür.

5

In [25]:
np.array([[0,1],[2,3]]).size

4

## np.array().dtype

In [26]:
np.array([1,2,3]).dtype # array içerisindeki elemanların veri türünü döndürür.

dtype('int32')

In [27]:
np.array([1.0, 2.0, 3.0]).dtype

dtype('float64')

# En çok kullanılan Numpy Metodları

## np.arange()

In [28]:
np.arange(1,20) # tıpkı python'daki range() fonksiyonu gibi...

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [29]:
np.arange(0,50,5) # 5'er 5'er atlayarak...

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

## np.zeros()

In [30]:
np.zeros(10) # 10 tane sıfır'ın olduğu bir array oluşturuyor...

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## np.ones()

In [31]:
np.ones(10) # 10 tane 1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [32]:
np.zeros((2,2)) # 2x2 lik bir matriste tüm elemanlar SIFIR.

array([[0., 0.],
       [0., 0.]])

In [33]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## np.full()

In [34]:
np.full((3,5), 7)  # bu metodla 7 değerlerinden oluşan 3x5'lik bir matrix oluşturabiliriz.

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

## np.linspace()

In [35]:
np.linspace(0,100,5) # 0 ile 100 arası değerleri 4 parçaya bölerek 5 elemanlı yeni bir array yapıyor.

array([  0.,  25.,  50.,  75., 100.])

## np.eye()

In [36]:
np.eye(6) # 6x6'lık birim matris oluşturuyor.

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

## np.random.normal()

In [37]:
np.random.normal(0,1,(3,4)) # ortalaması 0, varyansı 1 olan 3x4'lük bir matris döndürür.

array([[-1.13597297,  0.4367285 ,  0.18021105, -0.77927623],
       [ 0.63474415, -0.95654143,  0.82358934,  1.11465894],
       [-1.56422348,  1.08303415, -0.05538821, -0.13687387]])

## np.random.randint()

In [38]:
np.random.randint(0,10) # 0 ile 10 arasında (10 dahil değil) rastgele bir sayı tutar.

9

In [39]:
np.random.randint(10) # üsttekinin aynısıdır, sadece sıfır yazılmamış versiyonudur.

4

In [40]:
np.random.randint(2,12,3) # 2 ile 12 arası 3 adet sayı tutar ve bir array döndürür.

array([6, 6, 8])

In [41]:
np.random.randint(1,9,(3,4)) # 1 ile 9 arasında elemanları olan 3x4'lük bir matris döndürür.

array([[3, 8, 3, 3],
       [2, 5, 1, 7],
       [4, 7, 8, 6]])

In [42]:
# farklı yazım şekilleriyle de karşılaşabiliriz. 
np.random.randint(10, size=10) # 0 ile 10 arasında (10 dahil değil) 10 tane elemanı olan bir array döndürür.

array([0, 8, 3, 9, 4, 0, 5, 4, 8, 1])

## np.random.rand()

In [43]:
np.random.rand(5) # 0 ile 1 arası 5 adet değeri bir array içinde döndürür.

array([0.79668866, 0.29118426, 0.11329979, 0.82159052, 0.88837753])

## np.random.randn()

In [44]:
np.random.randn(5) # Gaussian (Normal) Dağılım ile 0 etrafında değerler üretir array döndürür.

array([-1.02174769,  1.10832858, -1.34347489, -0.40881784,  1.17525624])

## np.array().reshape()

In [45]:
np.array([1,2,3,4,5,6,7,8]).reshape(2,4) # 1x8'lik matrisi 2x4'lük matrise döndürür.

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [46]:
np.arange(1,9).reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [47]:
arr = np.arange(0,25) # önce 0'dan 25'e kadar (25 hariç) değerler üretti 1x25'lik bir matris oldu.
arr.reshape(5,5) # sonra bu matrisin şeklini değiştirerek 5x5'lik bir matrise çevirdi.


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [48]:
arr.reshape(4,5) # bunu yapamayız, çünkü array'in matrise tam yerleşmesi gerekiyor!

ValueError: cannot reshape array of size 25 into shape (4,5)

## np.array().max()

In [49]:
newArray = np.random.randint(1,100,10)

In [50]:
newArray

array([82, 68,  1, 16, 28, 49, 31, 73, 83, 71])

In [51]:
newArray.max() # array içindeki en büyük elemanı döndürür.

83

## np.array().min()

In [52]:
np.array([27,33,55,13,9]).min() # dizi içerisindeki minimum değeri döndürür.

9

In [53]:
newArray.min() 

1

## np.array().sum()

In [54]:
newArray.sum() # array içindeki elemanların sayısal toplamını döndürür.

502

## np.sort()

In [55]:
d = np.array([22,55,44,33])
d

array([22, 55, 44, 33])

In [56]:
np.sort(d) 
# sıralama işlemi yapar.
# fakat bunu uyguladığımızda d array'i değişmez!
# d array'ini değiştirmeden array değerlerini sıralayabiliriz.

array([22, 33, 44, 55])

## np.array().sort()

In [57]:
d.sort()
d # burada d array'i artık değişmiş olur.

array([22, 33, 44, 55])

## np.argsort()

In [58]:
d = np.array([22,55,44,33]) # aynı d array'imizi yeniden oluşturalım.
d

array([22, 55, 44, 33])

In [59]:
np.sort(d)

array([22, 33, 44, 55])

In [60]:
e = np.argsort(d) # bu işlemle eski d array'inin sıralandıktan sonraki indeks değişimini inceleyebiliriz.
e

array([0, 3, 2, 1], dtype=int64)

In [61]:
# np.argsort işlemi sonrası 
# sıralanmamış d ile sıralı d array'ini incelersek;

# 22 elemanı (eskide 0. indeks) sıralıda 0. indekse gitmiştir. (Yani aslında indeks değeri değişmemiş)
# 55 elemanı (eskide 1. indeks) sıralıda 3. indekse gitmiştir.
# 44 elemanı (eskide 2. indeks) sıralıda 2. indekse gitmiştir.
# 33 elemanı (eskide 3. indeks) sıralıda 1. indekse gitmiştir.


## np.array().mean()

In [62]:
newArray.mean() # array içindeki değerlerin ortalamasını döndürür.

50.2

## np.array().std()

In [63]:
newArray.std() # array içindeki elemanlara göre standart sapma hesabının sonucunu döndürür.

27.945661559533708

## np.array().var()

In [64]:
newArray.var() # varyans hesabı

780.96

## np.median()

In [65]:
np.median(newArray) # median değeri

58.5

## np.array().argmax()

In [66]:
newArray.argmax() # array içindeki en büyük sayının array içindeki indeksini döndürür.

8

## np.array().argmax()

In [67]:
newArray.argmin() # array içindeki en küçük sayının array içindeki indeksini döndürür.

2

## np.linalg.det()

In [68]:
dArray = np.array([[1,2],[3,4]]) # önce 2x2'lik bir matris oluşturuyoruz.
np.linalg.det(dArray)            # sonra bu matrisin determinantını buluyoruz.

-2.0000000000000004

In [69]:
round(np.linalg.det(dArray))    # sonucun daha yuvarlak çıkması için round() kullanılabilir.

-2.0

# Numpy Array Indeks İşlemleri

In [70]:
arr = np.arange(1,10)

In [71]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
arr[3] # indeksi 3 olan array elemanı

4

In [73]:
arr[1:5] # indeksi 1 olan elemandan, 5. elemana kadar gidiyor (5 dahil değil) ve array döndürüyor.

array([2, 3, 4, 5])

In [74]:
arr[0:4] # ilk elemandan indeksi 4 olan elemana kadar gidiyor (4 dahil değil) ve array döndürüyor.

array([1, 2, 3, 4])

In [75]:
arr[:4] # ilk elemandan indeksi 4 olan elemana kadar gidiyor (4 dahil değil) ve array döndürüyor.

array([1, 2, 3, 4])

In [76]:
arr[::2] # ilk elemandan son elemana kadar 2'şer 2'şer gidiyor ve array döndürüyor. 

array([1, 3, 5, 7, 9])

In [77]:
arr[3:] # 3 nolu indeksten son elemana kadar gidiyor ve array döndürüyor.

array([4, 5, 6, 7, 8, 9])

In [78]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
arr[:3]

array([1, 2, 3])

In [80]:
arr[:3] = 25 # ilk üç değeri 25 yapar.

In [81]:
arr

array([25, 25, 25,  4,  5,  6,  7,  8,  9])

In [82]:
arr = np.arange(1,10)

In [83]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
arr2 = arr # bunu yapınca arr2, arr'nin aynısı olur. arr2'de yapılan değişiklik arr'yi de etkiler.

In [85]:
arr2[:3] = 100

In [86]:
arr2

array([100, 100, 100,   4,   5,   6,   7,   8,   9])

In [87]:
arr

array([100, 100, 100,   4,   5,   6,   7,   8,   9])

In [88]:
# eğer bu şekilde birbirinin aynısı olmasını 
# ama aynı zamanda da birbirinden bağımsız olmasını istiyorsak, 
# arr.copy() komutunu kullanacağız.

In [89]:
arr = np.arange(1,10)

In [90]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## np.array().copy()

In [91]:
arr2 = arr.copy()

In [92]:
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
arr2[:3] = 10

In [94]:
arr2

array([10, 10, 10,  4,  5,  6,  7,  8,  9])

In [95]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
# birbirini etkilemedi.

In [97]:
newArray = np.arange(1,21)

In [98]:
newArray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [99]:
newArray = newArray.reshape((5,4))

In [100]:
newArray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [101]:
newArray[:,:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [102]:
newArray[::,:2] # tüm satırlar ve indeksi 2. ye kadar olan (2. dahil değil) sütunlar (farklı kullanımlar da var)

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18]])

In [103]:
newArray[:,:2] # 2. kullanım

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18]])

In [104]:
newArray[:2,::] # indeksi 2. ye kadar olan (2. dahil değil) satırlar ve tüm sütunlar (farklı kullanımlar da var)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [105]:
newArray[:2,:] # 2. kullanım

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [106]:
newArray[:2,] # 3. kullanım

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [107]:
newArray[2,3] # birinci sayı satır, ikinci sayı sütun indeksidir.

12

In [108]:
newArray[:2,:2] # birinci ifadede ilk satırdan 2 indeksli satıra kadar tüm satırları al demektir.
                # ikinci ifade de, ilk sütundan 2 indeksli sütuna kadar tüm sütunları al demektir.

array([[1, 2],
       [5, 6]])

In [109]:
newArray[:2,:]  # birinci ifadede ilk satırdan 2 indeksli satıra kadar tüm satırları al demektir.
                # ikinci ifade tüm sütunları al demektir.

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [110]:
newArray[:2] # üstteki kodla aynı sonucu verir, daha kısa halidir.

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

## Fancy Indeks

In [111]:
newArray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [112]:
newArray[:,1:3] # tüm satırlar ve 1. indeksten 3. indekse kadar (3. dahil değil) sütunlar döndürülüyor.

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19]])

In [113]:
# Fancy Indeks ile üstteki işlemin aynısını gerçekleştirebiliriz.
newArray[:,[1,2]] 
 
# [1,2] ifadesinde alınacak olan sütunlar tek tek ifade edilmiş oluyor.
# Yani indeksi 1 ve indeksi 2 olan sütunlar ayrı ayrı alınsın, denmiş oluyor.
# (":" yerine "," kondu ve array olarak yazıldığına dikkat ediyoruz!)

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19]])

In [114]:
newArray[[0,2],:] # bu işlemle 0. satırı ve 2. satırı ayrı ayrı alıp birleştirmiş olduk.

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [115]:
newArray[[0,2]] # 2. kullanım

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

# Numpy Array ile Mantıksal İşlemler

In [116]:
arr = np.arange(1,10)

In [117]:
arr > 3 # elemanın değeri 3'ten büyükse True, değilse False yazan yeni bir array döndürür.

array([False, False, False,  True,  True,  True,  True,  True,  True])

In [118]:
tf = arr > 3
tf

array([False, False, False,  True,  True,  True,  True,  True,  True])

In [119]:
arr[tf] # True ve False değerlerden oluşan array'i kullanarak arr array'ini filtreleyebiliriz.

array([4, 5, 6, 7, 8, 9])

In [120]:
tf

array([False, False, False,  True,  True,  True,  True,  True,  True])

In [121]:
arr[arr > 3] # son işlemi daha kısa şekilde böyle yapabiliriz.

array([4, 5, 6, 7, 8, 9])

In [122]:
arr <= 3

array([ True,  True,  True, False, False, False, False, False, False])

In [123]:
arr != 3

array([ True,  True, False,  True,  True,  True,  True,  True,  True])

In [124]:
arr == 5

array([False, False, False, False,  True, False, False, False, False])

## np.all()

In [125]:
np.all(arr > 3) # arr içindeki tüm elemanlar 3 değerinden büyük mü? (Cevap: Hayır)

False

In [126]:
np.all(arr > 0) # arr içindeki tüm elemanlar 0'dan büyük mü? (Cevap: Evet)

True

## np.any()

In [127]:
np.any(arr > 3) # arr içindeki herhangi bir eleman 3'ten büyük mü? (Cevap: Evet)

True

In [128]:
np.any(arr < 0) # arr içindeki herhangi bir eleman negatif mi? (Cevap: Hayır)

False

# Numpy Array ile Aritmetik İşlemler

In [129]:
arr1 = np.array([10,20,30,40,50,60])
arr2 = np.array([2,3,4,5,6,7])

In [130]:
arr1 + arr2 # her bir eleman, diğer array'de karşılık gelen elemanla toplanır.
            # toplama işleminin yapılabilmesi için iki array'in de eleman sayısı aynı olmalıdır.

array([12, 23, 34, 45, 56, 67])

In [131]:
arr1 - arr2 # aynı şekilde diğer işlemleri de yapabiliriz

array([ 8, 17, 26, 35, 44, 53])

In [132]:
arr1 * arr2

array([ 20,  60, 120, 200, 300, 420])

In [133]:
arr1 + 9 # arr1'deki her bir eleman 9 ile toplanır.

array([19, 29, 39, 49, 59, 69])

In [134]:
arr2 - 1 # arr2'deki her elemandan 1 çıkarılır.

array([1, 2, 3, 4, 5, 6])

In [135]:
arr1 # arr1 yeniden setlemediğimiz için son oluşturulduğundan beri aslında hiç değişmedi.

array([10, 20, 30, 40, 50, 60])

## np.sqrt()

In [136]:
np.sqrt(arr1) # her bir elemanın karekökünü alıp yeni bir array döndürür.

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781,
       7.74596669])

## np.add()

In [137]:
a = np.array([2,3,4,5])
np.add(a,3) # a içindeki her bir eleman 3 ile toplandı.

array([5, 6, 7, 8])

## np.subtract()

In [138]:
a = np.array([2,3,4,5])
np.subtract(a,3) # a içindeki her bir elemandan 3 çıkarıldı.

array([-1,  0,  1,  2])

## np.multiply()

In [139]:
a = np.array([2,3,4,5])
np.multiply(a,3) # a içindeki her bir eleman 3 ile çarpıldı.

array([ 6,  9, 12, 15])

## np.divide()

In [140]:
a = np.array([2,3,4,5])
np.divide(a,3) # a içindeki her bir eleman 3'e bölündü.

array([0.66666667, 1.        , 1.33333333, 1.66666667])

## np.power()

In [141]:
a = np.array([2,3,4,5])
np.power(a,3) # a içindeki her bir elemanın 3. kuvveti alındı.

array([  8,  27,  64, 125], dtype=int32)

## np.add.reduce()

In [142]:
a = np.array([2,3,4,5])
np.add.reduce(a) # a içindeki tüm elemanların toplamını verir.

14

## np.add.accumulate()

In [143]:
# üstteki np.add.reduce() işleminin her safhasını gösteren yeni bir array oluşturur.
np.add.accumulate(a)

array([ 2,  5,  9, 14], dtype=int32)

# Numpy Array'leri Birleştirmek

## np.array().concatenate()

In [144]:
a = np.array([1,2,3])
b = np.array([3,4,5])
c = np.array([5,6,7])
np.concatenate([a,b,c]) # a,b ve c arraylerini birleştirir.

array([1, 2, 3, 3, 4, 5, 5, 6, 7])

In [145]:
a2 = np.array([[1,2,3], [4,5,6]])
b2 = np.array([[1,1,1], [2,2,2]])
np.concatenate([a2,b2]) # a2 ve b2 iki boyutlu array'lerini birleştirir.

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 1],
       [2, 2, 2]])

In [146]:
np.concatenate([a2,b2], axis=1) # axis birleştirmede baz alınacak ekseni ifade eder. normalde 0'dır.

array([[1, 2, 3, 1, 1, 1],
       [4, 5, 6, 2, 2, 2]])

## np.array().vstack()

In [147]:
a = np.array([1,2,3])
b = np.array([[3,4,5], 
              [5,6,7]])

np.vstack([a,b]) # sütun sayısı aynı, satır sayısı farklı olan 
# array'leri DİKEY (vertical) olarak birleştirir.

# SÜTUN SAYISI AYNI OLMAZSA DİKEY OLARAK BİRLEŞTİREMEYİZ!

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

## np.array().hstack()

In [148]:
a = np.array([1,2,3]) 
b = np.array([[3,4,5], 
              [5,6,7]]) 

np.hstack([a,b]) # satır sayısı aynı sütun sayısı farklı olan 
# array'leri YATAY (horizontal) olarak birleştirir.

# Aynı örneği kullanırsak, burada hata meydana gelir. 
# Çünkü satır sayısı aynı değil!

ValueError: all the input arrays must have same number of dimensions

In [149]:
a = np.array([[1,2,3], 
              [0,0,0]])
b = np.array([[4,5,6,7], 
              [1,1,1,1]])

np.hstack([a,b]) # satır sayısı aynı sütun sayısı farklı olan 
# array'leri YATAY (horizontal) olarak birleştirir.

# SATIR SAYISI AYNI OLMAZSA YATAY OLARAK BİRLEŞTİREMEYİZ!

array([[1, 2, 3, 4, 5, 6, 7],
       [0, 0, 0, 1, 1, 1, 1]])

## Numpy Array'leri Parçalamak

In [150]:
a = np.array([1,2,3,4,5,6,7,8,9,0])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

## np.split()

In [151]:
np.split(a, (3,5)) 

# 0'dan 3. indekse kadar bir parça,
# 3. indeksten 5. indekse kadar bir parça,
# ve geriye ne kalıyorsa o da bir parça olacak şekilde parçalama işlemi yapar.

[array([1, 2, 3]), array([4, 5]), array([6, 7, 8, 9, 0])]

In [152]:
# Yukarıda oluşan 3 array'i direkt olarak değişkenlere tanımlayabiliriz.

x,y,z = np.split(a, (3,5))

In [153]:
x

array([1, 2, 3])

In [154]:
y

array([4, 5])

In [155]:
z

array([6, 7, 8, 9, 0])

## np.vsplit()

In [156]:
z = np.array([[0,1,2,3],
              [5,6,7,8],
              [9,10,11,12],
              [13,14,15,16]]) # 4x4'lük bir matris olsun.
z

array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [157]:
np.vsplit(z, [2]) 
# dikey olarak 2. indekse kadar gidip onu bir parça yapıyor. 
# geriye kalanlar da diğer parça oluyor.

[array([[0, 1, 2, 3],
        [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [158]:
np.vsplit(z, [3])

[array([[ 0,  1,  2,  3],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]), array([[13, 14, 15, 16]])]

In [159]:
z

array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [160]:
bir, iki = np.vsplit(z, [2])

In [161]:
bir

array([[0, 1, 2, 3],
       [5, 6, 7, 8]])

In [162]:
iki

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

## np.hsplit()

In [163]:
z

array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [164]:
np.hsplit(z, [2]) 
# yatay olarak 2. indekse kadar gidip onu bir parça yapıyor. 
# geriye kalanlar da diğer parça oluyor.

[array([[ 0,  1],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]), array([[ 2,  3],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [165]:
üç, dört = np.hsplit(z, [2])

In [166]:
üç

array([[ 0,  1],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [167]:
dört

array([[ 2,  3],
       [ 7,  8],
       [11, 12],
       [15, 16]])